name: Deploy

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ID_TOKEN: ${{ secrets.ID_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: pnmp install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Setup clasp
        working-directory: deployment
        run: |
          bash setup.sh
          bash setup_claspjson.sh
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Push
        run: pnpm run push --force
      - name: Deploy
        run: pnpm run deploy -d ${{ github.event.head_commit.message }}
